# Custom Language File for Launcher Customizer

[ejs.app]
title = "Zoo"

[ejs.landing]
mediaGitHubURL = "https://github.com/YoCsusu/Zoo"
mediaXURL = "https://twitter.com/Asghans"
mediaInstagramURL = "https://www.instagram.com/asghans"
mediaYouTubeURL = "https://www.youtube.com/@Asghans"
mediaDiscordURL = "https://discord.com/invite/DwppCMZZeM"
mediaTwitchURL = "https://www.twitch.tv/asghans"
mediaTikTokURL = "https://www.tiktok.com/@asghans"

[ejs.settings]
sourceGithubLink = "https://github.com/YoCsusu/Zoo"
supportLink = "https://github.com/YoCsusu/Zoo/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR LE ZOO"
welcomeDescription = "Le Zoo est un serveur Minecraft moddé conçu pour offrir une expérience de jeu unique et immersive. Grâce à une sélection de mods soigneusement choisis, explorez de nouvelles dimensions, affrontez des créatures inédites et construisez sans limites. Rejoignez notre communauté et vivez l'aventure Minecraft comme jamais auparavant."
welcomeDescCTA = "Plus que quelques clics pour rejoindre le Zoo."
