[ejs.landing]
updateAvailableTooltip = "Mise a jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Parametres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTUS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur selectionne"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Recherche d'actualites.."
newsErrorFailedSpan = "Impossible de charger les actualites"
newsErrorRetryButton = "Reessayer"
newsErrorNoneSpan = "Aucune actualite"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublie ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoye directement a Mojang et n'est jamais stocke."
loginPasswordDisclaimer2 = "{appName} n'est pas affilie a Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Selectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Selectionner un compte"
accountSelectConfirm = "Selectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Parametres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Lanceur"
navAbout = "A propos"
navUpdates = "Mises a jour"
navDone = "Termine"
tabAccountHeaderText = "Parametres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gerez les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Parametres Minecraft"
minecraftTabHeaderDesc = "Options liees au lancement du jeu."
gameResolutionTitle = "Resolution du jeu"
launchFullscreenTitle = "Lancer en plein ecran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le jeu de maniere detachee du lanceur."
launchDetachedDesc = "Si le jeu n'est pas detache, fermer le lanceur fermera aussi le jeu."
tabModsHeaderText = "Parametres des mods"
tabModsHeaderDesc = "Activer ou desactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods manuels"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou desactiver les shaders. Attention, les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalises ici."
selectShaderpack = "Selectionner un pack de shaders"
tabJavaHeaderText = "Parametres Java"
tabJavaHeaderDesc = "Gerer la configuration Java (avance)."
memoryTitle = "Memoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandee est de 3 gigaoctets. Definir les valeurs minimale et maximale identiques peut reduire les lags."
memoryTotalTitle = "Totale"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Executable Java"
javaExecSelDialogTitle = "Selectionner l'executable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'executable Java est verifie avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplementaires"
jvmOptsDesc = "Options a fournir a la JVM au demarrage. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas etre inclus."
launcherTabHeaderText = "Parametres du lanceur"
launcherTabHeaderDesc = "Options liees au lanceur lui-meme."
allowPrereleaseTitle = "Autoriser les mises a jour pre-release."
allowPrereleaseDesc = "Les pre-releases incluent de nouvelles fonctionnalites qui n'ont peut-etre pas ete entierement testees ou integrees.<br>Cette option sera toujours activee si vous utilisez une version pre-release."
dataDirectoryTitle = "Repertoire de donnees"
selectDataDirectory = "Selectionner le repertoire de donnees"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockes dans le repertoire de donnees.<br>Les captures d'ecran et les sauvegardes de mondes sont stockees dans le dossier d'instance de la configuration serveur correspondante."
aboutTabHeaderText = "A propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises a jour du lanceur"
launcherUpdatesHeaderDesc = "Telecharger, installer et consulter les mises a jour du lanceur."
checkForUpdates = "Rechercher des mises a jour"
whatsNew = "Nouveautes"
updateReleaseNotes = "Notes de mise a jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Deconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCES"
tryAgain = "Reessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de details."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur au lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de details."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte selectionne"

[js.landing.selectedServer]
noSelection = "Aucun serveur selectionne"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Verification du systeme.."
noCompatibleJava = "Aucune installation<br>Java compatible trouvee"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation 64 bits de Java {major}. Voulez-vous que nous en installions une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Preparation du telechargement de Java.."
javaDownloadFailureTitle = "Erreur lors du telechargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de details."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = "Une installation x64 valide de Java {major} est requise pour lancer.<br><br>Veuillez consulter notre <a href=\"https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">Guide de gestion Java</a> pour les instructions d'installation manuelle de Java."
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK telecharge a un hash incorrect, le fichier est peut-etre corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installe !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Voir la console (CTRL + Shift + i) pour plus de details."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur au lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de details."
validatingFileIntegrity = "Verification de l'integrite des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la verification des fichiers"
downloadingFiles = "Telechargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur lors du telechargement des fichiers"
preparingToLaunch = "Preparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu etre telecharge correctement. Le jeu ne peut donc pas se lancer.<br><br>Pour resoudre ce probleme, desactivez temporairement votre antivirus et relancez le jeu.<br><br>Si vous avez le temps, veuillez <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler le probleme</a> et nous indiquer quel antivirus vous utilisez. Nous les contacterons pour tenter de resoudre le probleme."
doneEnjoyServer = "Termine. Bon jeu !"
checkConsoleForDetails = "Veuillez verifier la console (CTRL + Shift + i) pour plus de details."

[js.landing.news]
checking = "Recherche d'actualites"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Connexion au serveur !"
joined = "En jeu !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "L'authentification Microsoft a echoue. Veuillez reessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "La deconnexion Microsoft a echoue. Veuillez reessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selectionner le compte"
selectedButton = "Compte selectionne &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C'est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le lanceur, vous devez etre connecte a au moins un compte. Vous devrez vous reconnecter apres.<br><br>Etes-vous sur de vouloir vous deconnecter ?"
confirmButton = "Je suis sur"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Selectionner le compte"
selectedAccount = "Compte selectionne âœ“"
logout = "Deconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Echec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas en cours d'utilisation et reessayez."
failedToggleTitle = "Echec de l'activation/desactivation<br>d'un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Selectionne : Java {version} ({vendor})"
invalidSelection = "Selection invalide"
requiresJava = "Necessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pre-release disponible"
downloadingButton = "Telechargement.."
downloadButton = "Telecharger depuis GitHub<span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Fermez le lanceur et executez le dmg pour mettre a jour.</span>"
latestVersionTitle = "Vous utilisez la derniere version"
checkForUpdatesButton = "Rechercher des mises a jour"
checkingForUpdatesButton = "Recherche de mises a jour.."

[js.settings.msftLogin]
errorTitle = "Echec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez reessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l'index de distribution"
fatalErrorMessage = "La connexion a nos serveurs n'a pas pu etre etablie pour telecharger l'index de distribution. Aucune copie locale n'a pu etre chargee. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernieres informations sur le serveur. Le lanceur ne peut pas demarrer sans celui-ci. Assurez-vous d'etre connecte a Internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Echec du rafraichissement de la connexion"
failedMessage = "Nous n'avons pas pu rafraichir la connexion pour <strong>{account}</strong>. Veuillez selectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu rafraichir la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Selectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mises a jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Rechercher des mises a jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configure"
noProfileDesc = "Votre compte Microsoft n'a pas encore de profil Minecraft configure. Si vous avez recemment achete le jeu ou l'avez obtenu via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore achete le jeu, vous pouvez le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'a aucun compte Xbox associe."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays ou Xbox Live n'est pas disponible ou est interdit."
under18Title = "Erreur de connexion :<br>Approbation parentale requise"
under18Desc = "Les comptes des utilisateurs de moins de 18 ans doivent etre ajoutes a une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Methode non autorisee"
methodNotAllowedDesc = "Methode non autorisee. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Non trouve"
notFoundDesc = "Le point d'authentification n'a pas ete trouve. Veuillez signaler ce probleme."
accountMigratedTitle = "Erreur de connexion :<br>Compte migre"
accountMigratedDesc = "Vous avez tente de vous connecter avec un compte migre. Reessayez en utilisant l'email du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'email ou le mot de passe que vous avez saisi est incorrect. Veuillez reessayer."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte recemment. Veuillez reessayer plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'acces fourni est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Jeton deja attribue"
tokenHasProfileDesc = "Le jeton d'acces a deja un profil attribue. La selection de profils n'est pas encore implementee."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur ou le mot de passe n'a pas ete soumis, ou le mot de passe fait moins de 3 caracteres."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de media non supporte"
unsupportedMediaTypeDesc = "Type de media non supporte. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migre"
accountGoneDesc = "Le compte a ete migre vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur de connexion :<br>Inaccessible"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Assurez-vous qu'ils sont en ligne et que vous etes connecte a Internet."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non achete"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas achete Minecraft. Vous pouvez l'acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de details."
